2021-07-17 22:34:06,912 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 20:58:27,126 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:10:24,838 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:10:48,301 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:27:38,491 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:29:31,591 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:34:46,201 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:40:41,714 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:43:35,103 ERROR: Exception on /user/vit [GET] [in /home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vitaly/python/microblog/app/routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/vitaly/python/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/vitaly/python/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/vitaly/python/microblog/app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-07-18 21:44:58,885 ERROR: Exception on /user/vit [GET] [in /home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vitaly/python/microblog/app/routes.py", line 73, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/templating.py", line 150, in render_template
    ctx.app,
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/vitaly/python/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/vitaly/python/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/vitaly/python/microblog/app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-07-18 21:49:35,940 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:57:26,835 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 21:57:41,933 ERROR: Exception on /user/vit [GET] [in /home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py:1455]
Traceback (most recent call last):
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/vitaly/python/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/vitaly/python/microblog/app/routes.py", line 73, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2021-07-18 21:59:59,610 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 22:01:35,262 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 22:17:43,918 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 22:23:53,366 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
2021-07-18 22:26:03,994 INFO: Microblog startup [in /home/vitaly/python/microblog/app/__init__.py:28]
